packages:
  - "."

allowBuilds:
  bufferutil: true
  esbuild: true
  keccak: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true

minimumReleaseAgeExclude:
  - viem@2.53.1

onlyBuiltDependencies:
  - bufferutil
  - esbuild
  - keccak
  - sharp
  - unrs-resolver
  - utf-8-validate
