"use client";
import { useState } from "react";
import { useAccount,useConnect,useDisconnect } from "wagmi";
import { Lock,ArrowUpRight,ShieldCheck,Landmark,Vote,Wallet,EyeOff,Plus,Clock3 } from "lucide-react";

const campaigns=[
 {name:"CIPHER LABS",tag:"AI INFRASTRUCTURE",desc:"Private verifiable inference for autonomous market agents.",days:11,investors:28,share:"4.5%",tone:"lime"},
 {name:"NULL SYSTEMS",tag:"ZERO-KNOWLEDGE",desc:"Proof orchestration for modular execution networks.",days:18,investors:41,share:"6.0%",tone:"blue"},
 {name:"DARK MATTER",tag:"CONFIDENTIAL DEFI",desc:"Institutional credit markets without position leakage.",days:7,investors:19,share:"3.25%",tone:"amber"}
];
export function StealthApp(){const{address,isConnected}=useAccount();const{connect,connectors}=useConnect();const{disconnect}=useDisconnect();const[view,setView]=useState<"market"|"portfolio"|"raise">("market");const[selected,setSelected]=useState(0);
 return <main><nav><div className="logo"><span><Lock size={15}/></span>STEALTHFUND</div><div className="links"><button onClick={()=>setView("market")}>Explore</button><button onClick={()=>setView("portfolio")}>Portfolio</button><button className="raise" onClick={()=>setView("raise")}><Plus size={14}/> Start a raise</button>{isConnected?<button className="connect" onClick={()=>disconnect()}>{address?.slice(0,6)}…{address?.slice(-4)}</button>:<button className="connect" onClick={()=>connect({connector:connectors[0]})}>Connect</button>}</div></nav>
 {view==="market"&&<><header><div className="kicker">PRIVATE MARKETS / PUBLIC ASSURANCE</div><h1>Capital without<br/><span>the exposure.</span></h1><p>Confidential startup financing on Ethereum. Commitments, participation and votes stay encrypted while execution remains verifiable.</p><div className="metrics"><div><b>ENCRYPTED</b><span>Commitments</span></div><div><b>PRIVATE</b><span>Positions</span></div><div><b>VERIFIABLE</b><span>Settlement</span></div></div></header>
 <section className="market"><div className="sectionhead"><div><small>LIVE OPPORTUNITIES</small><h2>Confidential raises</h2></div><p>Funding totals stay encrypted until campaign resolution.</p></div><div className="cards">{campaigns.map((c,i)=><article key={c.name} className={selected===i?"selected":""} onClick={()=>setSelected(i)}><div className={`visual ${c.tone}`}><span>{String(i+1).padStart(2,"0")}</span><EyeOff/></div><div className="content"><small>{c.tag}</small><h3>{c.name}</h3><p>{c.desc}</p><div className="terms"><span><b>{c.days}D</b> remaining</span><span><b>{c.investors}</b> participants</span><span><b>{c.share}</b> revenue pool</span></div><button>Review private raise <ArrowUpRight size={16}/></button></div></article>)}</div></section>
 <section className="detail"><div><small>SELECTED OPPORTUNITY</small><h2>{campaigns[selected].name}</h2><p>Commit mock confidential USD and receive encrypted, non-transferable participation units. Your position is visible only to your wallet.</p><div className="safety"><span><ShieldCheck/> User-only decryption</span><span><Landmark/> Contract escrow</span><span><Vote/> Private weighted voting</span></div></div><div className="commit"><div className="commithead"><Wallet/><span>CONFIDENTIAL COMMITMENT</span></div><label>Amount in cUSD<div><input placeholder="0.00" inputMode="decimal"/><b>cUSD</b></div></label><div className="hiddenrow"><span>Campaign total</span><b>ENCRYPTED</b></div><div className="hiddenrow"><span>Your position</span><b>{isConnected?"READY TO DECRYPT":"CONNECT WALLET"}</b></div><button disabled={!isConnected}>Encrypt & commit <ArrowUpRight size={16}/></button><small>Encryption is generated locally. No plaintext amount is sent to StealthFund.</small></div></section></>}
 {view==="portfolio"&&<section className="panel"><small>INVESTOR VAULT</small><h1>Your private positions.</h1><div className="empty"><EyeOff/><h3>{isConnected?"No indexed positions yet":"Wallet required"}</h3><p>{isConnected?"Commit to a live raise to create confidential participation units.":"Connect the wallet that owns your encrypted commitments."}</p></div></section>}
 {view==="raise"&&<section className="panel"><small>FOUNDER CONSOLE</small><h1>Structure a private raise.</h1><div className="raiseform"><label>Campaign name<input placeholder="Company or protocol"/></label><label>Revenue share<input placeholder="e.g. 5%"/></label><label>Commitment deadline<input type="date"/></label><label>Public terms hash<input placeholder="0x…"/></label><label className="wide">Public thesis<textarea placeholder="Describe the opportunity without exposing investor data."/></label><button disabled={!isConnected}>Create Sepolia campaign <ArrowUpRight size={16}/></button></div></section>}
 <section className="protocol"><div><small>PROTOCOL MODEL</small><h2>Private values.<br/>Public state.</h2></div><ol><li><span>01</span><b>Encrypt</b><p>The browser encrypts commitments through the Zama relayer SDK.</p></li><li><span>02</span><b>Compute</b><p>FHE contracts update totals and vote weights without decrypting them.</p></li><li><span>03</span><b>Settle</b><p>Only outcomes become public. Positions stay accessible to their owners.</p></li></ol></section>
 <footer><div className="logo">STEALTHFUND</div><span>Ethereum Sepolia · Zama FHE</span><p>Testnet software. Revenue participation units are not legal equity or securities.</p></footer></main>}
