"use client";
import { useState } from "react";
import { useAccount,useConnect,useDisconnect,usePublicClient,useWriteContract } from "wagmi";
import { Lock,ArrowUpRight,ShieldCheck,Landmark,Vote,Wallet,EyeOff,Plus } from "lucide-react";
import { parseUnits, toHex, keccak256, stringToHex } from "viem";
import { RelayerWeb, SepoliaConfig } from "@zama-fhe/sdk";

const CUSD=(process.env.NEXT_PUBLIC_CUSD_ADDRESS||"0x42eB87cb7d1bb5A83cE15b4f2a34e1722Bd43f4b") as `0x${string}`;
const FACTORY=(process.env.NEXT_PUBLIC_FACTORY_ADDRESS||"0xBF5163D30a914d907BE2fB9973940668e404127e") as `0x${string}`;
const LIVE_CAMPAIGN="0x836Ea41903aC2aee56c0A7AFc403D83c951bDdA6" as const;
const tokenAbi=[{"type":"function","name":"faucet","stateMutability":"nonpayable","inputs":[],"outputs":[]},{"type":"function","name":"setOperator","stateMutability":"nonpayable","inputs":[{"name":"operator","type":"address"},{"name":"approved","type":"bool"}],"outputs":[]}] as const;
const campaignAbi=[{"type":"function","name":"commit","stateMutability":"nonpayable","inputs":[{"name":"encryptedAmount","type":"bytes32"},{"name":"proof","type":"bytes"}],"outputs":[]}] as const;
const factoryAbi=[{"type":"function","name":"createCampaign","stateMutability":"nonpayable","inputs":[{"name":"metadataHash","type":"bytes32"},{"name":"termsHash","type":"bytes32"},{"name":"startAt","type":"uint64"},{"name":"endAt","type":"uint64"},{"name":"threshold","type":"uint64"},{"name":"salt","type":"bytes32"}],"outputs":[{"name":"campaign","type":"address"}]}] as const;

const campaigns=[
 {name:"CIPHER LABS",tag:"AI INFRASTRUCTURE",desc:"Private verifiable inference for autonomous market agents.",days:11,investors:28,share:"4.5%",tone:"lime"},
 {name:"NULL SYSTEMS",tag:"ZERO-KNOWLEDGE",desc:"Proof orchestration for modular execution networks.",days:18,investors:41,share:"6.0%",tone:"blue"},
 {name:"DARK MATTER",tag:"CONFIDENTIAL DEFI",desc:"Institutional credit markets without position leakage.",days:7,investors:19,share:"3.25%",tone:"amber"}
];
export function StealthApp(){const{address,isConnected}=useAccount();const{connect,connectors}=useConnect();const{disconnect}=useDisconnect();const publicClient=usePublicClient();const{writeContractAsync}=useWriteContract();const[view,setView]=useState<"market"|"portfolio"|"raise">("market");const[selected,setSelected]=useState(0);const[amount,setAmount]=useState("");const[status,setStatus]=useState("Ready");const[raiseName,setRaiseName]=useState("");const[deadline,setDeadline]=useState("");
 async function faucet(){if(!publicClient)return;setStatus("Requesting confidential test USD…");try{const hash=await writeContractAsync({address:CUSD,abi:tokenAbi,functionName:"faucet"});await publicClient.waitForTransactionReceipt({hash});setStatus("10,000 cUSD issued privately")}catch(e){setStatus(e instanceof Error?e.message:"Faucet failed")}}
 async function commit(){if(!address||!publicClient||!amount)return;setStatus("Approving campaign operator…");try{let hash=await writeContractAsync({address:CUSD,abi:tokenAbi,functionName:"setOperator",args:[LIVE_CAMPAIGN,true]});await publicClient.waitForTransactionReceipt({hash});setStatus("Encrypting locally with Zama FHE…");const relayer=new RelayerWeb({transports:{[SepoliaConfig.chainId]:SepoliaConfig},getChainId:async()=>SepoliaConfig.chainId});const encrypted=await relayer.encrypt({values:[{value:parseUnits(amount,6),type:"euint64"}],contractAddress:LIVE_CAMPAIGN,userAddress:address});setStatus("Confirm confidential commitment…");hash=await writeContractAsync({address:LIVE_CAMPAIGN,abi:campaignAbi,functionName:"commit",args:[toHex(encrypted.handles[0]),toHex(encrypted.inputProof)]});await publicClient.waitForTransactionReceipt({hash});relayer.terminate();setStatus(`Confirmed · ${hash.slice(0,10)}…`);setAmount("")}catch(e){setStatus(e instanceof Error?e.message:"Commitment failed")}}
 async function createRaise(){if(!publicClient||!raiseName||!deadline)return;setStatus("Creating campaign on Sepolia…");try{const now=Math.floor(Date.now()/1000);const end=Math.floor(new Date(deadline).getTime()/1000);const hash=await writeContractAsync({address:FACTORY,abi:factoryAbi,functionName:"createCampaign",args:[keccak256(stringToHex(raiseName)),keccak256(stringToHex(`${raiseName}:revenue-share-v1`)),BigInt(now),BigInt(end),50_000_000_000n,keccak256(stringToHex(`${raiseName}:${address}:${Date.now()}`))]});await publicClient.waitForTransactionReceipt({hash});setStatus(`Campaign deployed · ${hash.slice(0,10)}…`)}catch(e){setStatus(e instanceof Error?e.message:"Creation failed")}}
 return <main><nav><div className="logo"><span><Lock size={15}/></span>STEALTHFUND</div><div className="links"><button onClick={()=>setView("market")}>Explore</button><button onClick={()=>setView("portfolio")}>Portfolio</button><button className="raise" onClick={()=>setView("raise")}><Plus size={14}/> Start a raise</button>{isConnected?<button className="connect" onClick={()=>disconnect()}>{address?.slice(0,6)}…{address?.slice(-4)}</button>:<button className="connect" onClick={()=>connect({connector:connectors[0]})}>Connect</button>}</div></nav>
 {view==="market"&&<><header><div className="kicker">PRIVATE MARKETS / PUBLIC ASSURANCE</div><h1>Capital without<br/><span>the exposure.</span></h1><p>Confidential startup financing on Ethereum. Commitments, participation and votes stay encrypted while execution remains verifiable.</p><div className="metrics"><div><b>ENCRYPTED</b><span>Commitments</span></div><div><b>PRIVATE</b><span>Positions</span></div><div><b>VERIFIABLE</b><span>Settlement</span></div></div></header>
 <section className="market"><div className="sectionhead"><div><small>LIVE OPPORTUNITIES</small><h2>Confidential raises</h2></div><p>Funding totals stay encrypted until campaign resolution.</p></div><div className="cards">{campaigns.map((c,i)=><article key={c.name} className={selected===i?"selected":""} onClick={()=>setSelected(i)}><div className={`visual ${c.tone}`}><span>{String(i+1).padStart(2,"0")}</span><EyeOff/></div><div className="content"><small>{c.tag}</small><h3>{c.name}</h3><p>{c.desc}</p><div className="terms"><span><b>{c.days}D</b> remaining</span><span><b>{i===0?"LIVE":"SOON"}</b> Sepolia</span><span><b>{c.share}</b> revenue pool</span></div><button>Review private raise <ArrowUpRight size={16}/></button></div></article>)}</div></section>
 <section className="detail"><div><small>SELECTED OPPORTUNITY</small><h2>{campaigns[selected].name}</h2><p>{selected===0?"A live Sepolia campaign. Commit confidential USD and receive encrypted participation units visible only to your wallet.":"This opportunity is a product preview; select Cipher Labs for the live onchain flow."}</p><div className="safety"><span><ShieldCheck/> User-only decryption</span><span><Landmark/> Contract escrow</span><span><Vote/> Private weighted voting</span></div></div><div className="commit"><div className="commithead"><Wallet/><span>CONFIDENTIAL COMMITMENT</span></div><label>Amount in cUSD<div><input placeholder="0.00" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/><b>cUSD</b></div></label><div className="hiddenrow"><span>Campaign total</span><b>ENCRYPTED</b></div><div className="hiddenrow"><span>Status</span><b>{status}</b></div><button className="faucet" disabled={!isConnected} onClick={faucet}>Get test cUSD</button><button disabled={!isConnected||!amount||selected!==0} onClick={commit}>Encrypt & commit <ArrowUpRight size={16}/></button><small>Encryption is generated locally. No plaintext amount is sent to StealthFund.</small></div></section></>}
 {view==="portfolio"&&<section className="panel"><small>INVESTOR VAULT</small><h1>Your private positions.</h1><div className="empty"><EyeOff/><h3>{isConnected?"No indexed positions yet":"Wallet required"}</h3><p>{isConnected?"Commit to a live raise to create confidential participation units.":"Connect the wallet that owns your encrypted commitments."}</p></div></section>}
 {view==="raise"&&<section className="panel"><small>FOUNDER CONSOLE</small><h1>Structure a private raise.</h1><div className="raiseform"><label>Campaign name<input placeholder="Company or protocol" value={raiseName} onChange={e=>setRaiseName(e.target.value)}/></label><label>Revenue share<input value="5% testnet default" readOnly/></label><label>Commitment deadline<input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><label>Funding threshold<input value="50,000 cUSD" readOnly/></label><label className="wide">Public thesis<textarea placeholder="Describe the opportunity without exposing investor data."/></label><div className="wide hiddenrow"><span>Status</span><b>{status}</b></div><button disabled={!isConnected||!raiseName||!deadline} onClick={createRaise}>Create Sepolia campaign <ArrowUpRight size={16}/></button></div></section>}
 <section className="protocol"><div><small>PROTOCOL MODEL</small><h2>Private values.<br/>Public state.</h2></div><ol><li><span>01</span><b>Encrypt</b><p>The browser encrypts commitments through the Zama relayer SDK.</p></li><li><span>02</span><b>Compute</b><p>FHE contracts update totals and vote weights without decrypting them.</p></li><li><span>03</span><b>Settle</b><p>Only outcomes become public. Positions stay accessible to their owners.</p></li></ol></section>
 <footer><div className="logo">STEALTHFUND</div><span>Ethereum Sepolia · Zama FHE</span><p>Testnet software. Revenue participation units are not legal equity or securities.</p></footer></main>}
