[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
solc_version = "0.8.27"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
allow_paths = ["../node_modules"]

remappings = [
  "@fhevm/=../node_modules/@fhevm/",
  "@openzeppelin/=../node_modules/@openzeppelin/",
  "encrypted-types/=../node_modules/.pnpm/@fhevm+solidity@0.11.1/node_modules/encrypted-types/"
]
